### PR TITLE
Prefix Option - allow user to define the process name prefix that is sta...

### PR DESCRIPTION
**Pull request by rbowman222222**
I did a single commit and did a push --force.

Thanks,
Rich

### CODE REVIEW

**Comment by blackjid** [comment]
Why did you start a new pull request?? that was weird, please use this same PR to add the las changes....

**Comment by rbowman222222** [comment]
I fixed the 'join' part and the extra space in the README file.  And this
push --force.
Thanks,Rich


Sorry this is the first time I have done a Git fork, pull , and push
--force.

**Comment by blackjid** [comment]
Thanks!... Just for you to know, it was not necessary the push --force.... that is necessary if you want to rewrite de history. For example if you want to squash the commits in one commit. 

I will merge as is now.. thanks!

**Comment by blackjid** [comment]
released on 1.3.0

**Comment by rbowman222222** [comment]
thanks

**Pull request merged**
