### PR TITLE
Stop multiple workers right

### PR DESCRIPTION
**Pull request by faridco**
Delayed_job stop command should have same `-n <count>` argument as start command

### CODE REVIEW

**Comment by 164c** [comment]
+1

**Comment by blackjid** [comment]
what is the problem this argument is not passed to the stop command?

**Comment by afhbl** [comment]
`delayed_job stop` will not stop any instances if start command was called with count > 1 (e.g. `delayed_job start -n 2`)

**Comment by blackjid** [comment]
@afhbl I was doing some test and what I can see is that all processes should be stopped when calling `delayed_job stop` without the `-n` argument

[asciicast](https://asciinema.org/a/5s6fma5otl3b5rscf3vi75i6h)

Also the delayed job examples show that behaviour.
https://github.com/collectiveidea/delayed_job#running-jobs

Maybe is something else...

**Comment by afhbl** [comment]
having rails 4.2 with
```
delayed_job (4.0.6)
delayed_job_active_record (4.0.3)
```
>Rails 4: replace script/delayed_job with bin/delayed_job

so this is the reason maybe?

**Comment by blackjid** [comment]
you're right, it is different with rails 4.2, but the real difference is the `daemons` gem that it's being used.

I don't know how to handle this, I think the correct way to stop the workers is without the `-n` argument, and this is a delayed_job bug.

https://github.com/collectiveidea/delayed_job/issues/798

In my tests and based on the @ratdaddy comment https://github.com/collectiveidea/delayed_job/issues/798#issuecomment-96815090
if you lock the daemons gem to `1.1.9` the problem is gone and you can stop without any argument, but I don't know if there is a real dependency on a newer versions of daemons.

At least in the [delayed_job.gemspec](https://github.com/collectiveidea/delayed_job/blob/master/delayed_job.gemspec) there is no dependecy on a specific version.

**Comment by afhbl** [comment]
is that safe to pass `-n <count>` to stop command? for some reasons I can't downgrade `daemons` version

**Comment by blackjid** [comment]
why you couldn't?? I just added `gem 'daemons', '1.1.9'` to the gemfile and run `bundle install`.

I don't really know if there is any problems on passing this argument to the stop command. But I don't feel this is should fix in this gem. What do you think about that?

maybe we could add another option to override the arguments passed to each command.

**Comment by afhbl** [comment]
>why you couldn't?

have some stuff which depends on `daemons > 1.2`

btw it looks logical passing count arg to stop command, just because start and restart command requires such argument

another option is to check daemons version while constructing arguments to commands

**Comment by blackjid** [comment]
thanks! Sorry de delay!
fixed in [1.4.1](https://github.com/platanus/capistrano3-delayed-job/releases/tag/v1.4.1)

**Pull request closed without merging**
